baseURL = 'https://dark-kernel.web.app/'
languageCode = 'en-us'
title = 'Dark Kernel'
theme = 'terminal-theme'
pagination.pagerSize = 5
#paginate = 5


[author]
    name = "Sumit Patel"


[params]
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # set theme to full screen width
  #fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"
  enableSearch = true
  enableInlineShortcodes = true
  contentDir = "content/post"
  facebook = "https://www.facebook.com/"
  email = "darkkernel@tutamail.com"
  include_toc = true
  Toc = false
  show_comments = true 
  favicon = "/profile.jpg"


DisqusShortname = 'sumitpatel'

[social]
    twitter = 'sumitpatel'


    
    
[languages]
  [languages.en]
    [languages.en.params]
        title = "Sumit Patel"
        subtitle = "Just a personal site."
        keywords = ""
        copyright = ""
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Sumit Patel"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

      [[languages.en.menu.main]]
        identifier = "post"
        name = "Post"
        url = "/post"

      [[languages.en.menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes"

